sh ./install_jack2.sh
sh ./install_mod-ttymidi.sh
sh ./install_lv2_lilv.sh
sh ./install_lvtk.sh
sh ./install_mod-host.sh
sh ./install_mod-ui.sh
sh ./install_phantomjs.sh
sh ./install_mod-sdk.sh
sh ./install_modmeter.lv2.sh
sh ./install_step-seq.sh
sh ./install_dexed.sh
